### ISSUE TITLE
Disable memory cache

### ISSUE THREAD

**Issue by binary64** [pierrecabriere/next-apollo-hoc#2]
Greeting! Fantastic HOC. Loving it so far.

Is it possible to disable the memory cache? I refresh my app and it loads data, but I dont see it in Chrome inspector under Network or Application..

**Comment by pierrecabriere** [comment]
Hello @binary64,
Thank you for you support on this project.
It's normal that you can't see any activity under your Network inspector, because the data is fetched from the server. So the data is already cached when the page renders in your browser and, by default, Apollo will read this cache.
However, you can tell Apollo to refetch the query in your browser, or even not reading the cache.
To do this, please refers to the [`fetchPolicy` section](https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-fetchPolicy) in the Apollo doc.
Feel free to reopen this issue if you have any problem with this.
